{{- /*
If the operator configures the customObjects input variable, then create custom resources based on the given
definitions. If a list of definitions is provided, separate them using the YAML separator so they can all be executed
from the same template file.
*/ -}}

{{- if .Values.customObjects.enabled -}}
{{- range $name, $value := .Values.customObjects.definitions }}
---
{{ $value }}
{{- end }}
{{- end }}
